name: Test
on:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    environment: Test
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          
      - name: Print secret
        run: echo ${{ secrets.MY_SUPER_SECRET_ENV }}

      - name: Run test script
        env:
          MY_SUPER_SECRET_ENV: ${{ secrets.MY_SUPER_SECRET_ENV }}
        run: node main.js
